-- AddColumn: shipping cost fields for PricingSettings
ALTER TABLE "PricingSettings"
  ADD COLUMN IF NOT EXISTS "labelWeightPerM2Grams"    DECIMAL(10, 2) NOT NULL DEFAULT 150,
  ADD COLUMN IF NOT EXISTS "shippingTier1MaxKg"       DECIMAL(10, 2) NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "shippingTier1RateEur"     DECIMAL(10, 2) NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "shippingTier2MaxKg"       DECIMAL(10, 2) NOT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS "shippingTier2RateEur"     DECIMAL(10, 2) NOT NULL DEFAULT 9,
  ADD COLUMN IF NOT EXISTS "shippingTier3RateEur"     DECIMAL(10, 2) NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS "shippingHeavyThresholdKg" DECIMAL(10, 2) NOT NULL DEFAULT 100;
